name: Release LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
          
  create_release:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: PDF

      - name: Set release tag
        run: |
          latestTag=$(git tag -l 'v*' | sed 's/^v//' | sort -nr | head -n 1)
          newTag="v$((latestTag + 1))"
          echo "RELEASE_TAG=$newTag" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: ${{ env.RELEASE_TAG }}